# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_f.10086.cn	FALSE	/	FALSE	3510380684	UUID	f8caa36f-390e-4913-89b3-80027bf696a3
#HttpOnly_f.10086.cn	FALSE	/	FALSE	1370673037	cell_cookie	c1cf8a080cbaa4418907786612d70861|39faf6b0cc1983d6cf047a725e9bc6f5|030e913b2b8088e441e2be244b2f8be0|1
#HttpOnly_f.10086.cn	FALSE	/	FALSE	1370673037	loginstatusCookie	400
#HttpOnly_f.10086.cn	FALSE	/	FALSE	0	JSESSIONID	abcuNk5p9k3L8bGEM-s1t

curl -b 'UUID=b9c37c80-56e8-42f8-9edc-8c2990673bc5; cell_cookie=c1cf8a080cbaa4418907786612d70861|39faf6b0cc1983d6cf047a725e9bc6f5|030e913b2b8088e441e2be244b2f8be0|1; loginstatusCookie=400; JSESSIONID=abcRAxS204_9M8WmUot1t;' 'http://f.10086.cn/im5/index/loadGroupContactsAjax.action?'
